In [1]:
import numpy as np
from scipy import integrate
from scipy.linalg import expm
from matplotlib import pyplot as plt
from scipy import stats

In [2]:
A = np.array([
    [0, 1],
    [0, -1]
])

b_u = np.array([[0], [1]])
b_w = np.array([[0], [1]])

In [3]:
h = 0.1

A_d = expm(A * h)
print(A_d)

[[1.         0.09516258]
 [0.         0.90483742]]


In [4]:
t = np.linspace(0, 10, 100) # Need to match h!!

In [5]:
def for_W(x: np.ndarray) -> np.ndarray:
    return expm(A * x) @ b_w @ b_w.T @ expm(A.T * x)

In [6]:
A.shape

(2, 2)

In [7]:
b_w.T

array([[0, 1]])

In [8]:
W, __ = integrate.quad_vec(for_W, 0, h)
print(W)

[[0.00030946 0.00452796]
 [0.00452796 0.09063462]]


In [16]:
w = stats.multivariate_normal.rvs(np.array([0, 0]), W, 1)
print(w)

[0.0059003  0.22318203]


SyntaxError: invalid syntax (2468448305.py, line 1)